### ISSUE TITLE
pytorch_pretrained_bert/modeling.py name error -- PreTrainedBertModel

### ISSUE THREAD

**Issue by deesatz** [charles9n/bert-sklearn#1]
When I changed: 
import PreTrainedBertModel to
import BertPreTrainedModel as PreTrainedBertModel
seemed to be quick a temporary fix

**Comment by charles9n** [comment]
Newer version of pytorch_pretrained_bert uses BertPreTrainedModel, older version uses PreTrainedBertModel. Should be fixed now. Thanks.
