### ISSUE TITLE
some error in chinese NER

### ISSUE THREAD

**Issue by MenglinLu** [charles9n/bert-sklearn#6]

**Comment by charles9n** [comment]
What is the error you are seeing?

**Comment by MenglinLu** [comment]
Thanks for your reply.  The error that I met is: When I run the code 'model.get_max_token_len(X_train)', error : 'AttributeError: 'NoneType' object has no attribute 'tokenize''. In addition, when I run the code 'model.fit(X_train, y_train)' ,error 'AttributeError: 'NoneType' object has no attribute 'to''. I don't know if it's my own fault.  Hope to get your reply. Thank you very much.

**Comment by charles9n** [comment]
You are welcome!
I just ran 'ner_chinese.ipynb' and it runs ok for me.
Based on the error you are getting it seems like the tokenizer is not being loaded from the internet. I am wondering if your internet is down or you cant get to the s3 url where the vocab and model data reside.
After you define the model try this: 
>> model.load_tokenizer()  
>> print(model.tokenizer)
Tell me what you see with this print.
If this prints nothing,i.e None,, then the tokenizer never got loaded. If it gets loaded then it will return a BertTokenizer i.e <bert_sklearn.model.pytorch_pretrained.tokenization.BertTokenizer object at 0x....>

**Comment by MenglinLu** [comment]
Oh thank you. I will try and reply you then.

**Comment by MenglinLu** [comment]
Wow you are right. Thank you very much. I ignored that I was in the internal network and didn't load successfully. Now the problem is solved. Thanks again and thank you for the open source of this great library.

**Comment by charles9n** [comment]
You are very welcome! I am glad I could help.
