### ISSUE TITLE
URL for IMDb notebook

### ISSUE THREAD

**Issue by guydepauw** [charles9n/bert-sklearn#8]
Thanks for making this available! Great stuff!

Wanted to let you know about the dead link in your README.md:

`https://github.com/charles9n/bert-sklearn-tmp/blob/master/other_examples/IMDb.ipynb`

should be

`https://github.com/charles9n/bert-sklearn/blob/master/other_examples/IMDb.ipynb`

**Comment by charles9n** [comment]
You are welcome! Thanks for pointing that out. Just fixed it.

**Comment by charles9n** [comment]
Fixed link.
